version: '3.4'
services:
  scripts:
    build:
      context: ./
      dockerfile: Dockerfile.rscripts
    volumes:
      - ./data:/usr/local/src/data
  api:
    build:
      context: ./
      dockerfile: Dockerfile.node
    depends_on:
      - scripts
    volumes:
      - ./data:/usr/src/app/data
    environment:
      PORT: 8080
    ports:
      - '8080:80'
    stdin_open: true
    tty: true
