version: '3.4'
services:
  scripts:
    build:
      context: ./
      dockerfile: Dockerfile.rscripts
    volumes:
      - ./data:/usr/local/src/data
  web:
    build:
      context: ./
      dockerfile: Dockerfile.web
    depends_on:
      - scripts
    volumes:
      - ./data:/usr/src/app/data
    ports:
      - "80:80"
      - "9229:9229"
      - "9230:9230"
    stdin_open: true
    tty: true
